/* Atividade 3  Exercicio 05 - Faça um SELECT que retorne todes o/a(s) estudantes com a nota menor do que 7.0. */

CREATE DATABASE BD_ESCOLA;

USE BD_ESCOLA;

CREATE TABLE TB_ESTUDANTES(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
IDADE INT,
SERIE CHAR(255),
NOTA DOUBLE,
MATERIA CHAR(255),
PRIMARY KEY (ID)
);

SELECT * FROM TB_ESTUDANTES;

INSERT INTO TB_ESTUDANTES(NOME, IDADE, SERIE, NOTA, MATERIA) VALUES ('Fernando', 15,'8º', 9.5,'FISICA');
INSERT INTO TB_ESTUDANTES(NOME, IDADE, SERIE, NOTA, MATERIA) VALUES ('Jonas', 13,'6º', 4.8,'FISICA');
INSERT INTO TB_ESTUDANTES(NOME, IDADE, SERIE, NOTA, MATERIA) VALUES ('Marcos', 12,'5º', 5.0,'FISICA');
INSERT INTO TB_ESTUDANTES(NOME, IDADE, SERIE, NOTA, MATERIA) VALUES ('Lucia', 11,'4º', 6.8,'FISICA');
INSERT INTO TB_ESTUDANTES(NOME, IDADE, SERIE, NOTA, MATERIA) VALUES ('Bruno', 12,'5º', 3.0,'FISICA');
INSERT INTO TB_ESTUDANTES(NOME, IDADE, SERIE, NOTA, MATERIA) VALUES ('Vanessa', 15,'8º', 7.5,'FISICA');
INSERT INTO TB_ESTUDANTES(NOME, IDADE, SERIE, NOTA, MATERIA) VALUES ('Vinicius', 14,'7º', 8.0,'FISICA');
INSERT INTO TB_ESTUDANTES(NOME, IDADE, SERIE, NOTA, MATERIA) VALUES ('Camila', 11,'4º', 10,'FISICA');

SELECT * FROM TB_ESTUDANTES WHERE NOTA > 7; 

SELECT * FROM TB_ESTUDANTES WHERE NOTA < 7; 